CREATE DATABASE WEB;
USE WEB;

CREATE TABLE REGION
(
	r_id INT PRIMARY KEY,
	r_description VARCHAR(100) NOT NULL
)ENGINE=INNODB;

CREATE TABLE PROVINCIA
(
	pr_id INT PRIMARY KEY NOT NULL,
	pr_description VARCHAR(100) NOT NULL,
	r_id INT NOT NULL,
	
	CONSTRAINT `FK_region_provincia` FOREIGN KEY (`r_id`)
	REFERENCES REGION(`r_id`)
	ON DELETE RESTRICT
   ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE DISTRITO
(
	ds_id INT PRIMARY KEY NOT NULL,
	ds_description VARCHAR(100) NOT NULL,
	pr_id INT NOT NULL,
	
	CONSTRAINT `FK_provincia_distrito` FOREIGN KEY (`pr_id`)
	REFERENCES PROVINCIA(`pr_id`)
	ON DELETE RESTRICT
   ON UPDATE CASCADE
)ENGINE=INNODB;


CREATE TABLE LUGAR
(
	lg_id INT NOT NULL PRIMARY KEY,
	lg_nombre VARCHAR(100) NOT NULL,
	lg_description VARCHAR(100) NOT NULL,
	ds_id INT NOT NULL,
	
	CONSTRAINT `FK_distrito_lugar` FOREIGN KEY (`ds_id`)
	REFERENCES DISTRITO(`ds_id`)
	ON DELETE RESTRICT
   ON UPDATE CASCADE
   
)ENGINE=INNODB;


CREATE TABLE IMAGES
(
	img_id INT NOT NULL PRIMARY KEY,
	img_description VARCHAR(100) NOT NULL,
	img_uri VARCHAR(999) NOT NULL,
	lg_id INT NOT NULL,
	
	CONSTRAINT `FK_lugares_images` FOREIGN KEY (`lg_id`)
	REFERENCES LUGAR(`lg_id`)
	ON DELETE RESTRICT
   ON UPDATE CASCADE
   
)ENGINE=INNODB;

-- inserts

